# Generated by Django 3.2.8 on 2021-12-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
